In [2]:
import pandas as pd

In [4]:
df = pd.read_csv('/content/sample_data/california_housing_train.csv')

In [5]:
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0

In [6]:
df.tail()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17000 entries, 0 to 16999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           17000 non-null  float64
 1   latitude            17000 non-null  float64
 2   housing_median_age  17000 non-null  float64
 3   total_rooms         17000 non-null  float64
 4   total_bedrooms      17000 non-null  float64
 5   population          17000 non-null  float64
 6   households          17000 non-null  float64
 7   median_income       17000 non-null  float64
 8   median_house_value  17000 non-null  float64
dtypes: float64(9)
memory usage: 1.2 MB

In [8]:
df.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value'],
      dtype='object')

In [9]:
df.shape

(17000, 9)

In [11]:
df.describe()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
count,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000
mean,-119.562108,35.625225,28.589353,2643.664412,539.410824,1429.573941,501.221941,3.883578,207300.912353
std,2.005166,2.137340,12.586937,2179.947071,421.499452,1147.852959,384.520841,1.908157,115983.764387
min,-124.350000,32.540000,1.000000,2.000000,1.000000,3.000000,1.000000,0.499900,14999.000000
25%,-121.790000,33.930000,18.000000,1462.000000,297.000000,790.000000,282.000000,2.566375,119400.000000
50%,-118.490000,34.250000,29.000000,2127.000000,434.000000,1167.000000,409.000000,3.544600,180400.000000
75%,-118.000000,37.720000,37.000000,3151.250000,648.250000,1721.000000,605.250000,4.767000,265000.000000
max,-114.310000,41.950000,52.000000,37937.000000,6445.000000,35682.000000,6082.000000,15.000100,500001.000000

In [12]:
df.dtypes

longitude             float64
latitude              float64
housing_median_age    float64
total_rooms           float64
total_bedrooms        float64
population            float64
households            float64
median_income         float64
median_house_value    float64
dtype: object

In [13]:
df.isnull().sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
dtype: int64

In [14]:
df['longitude']

0       -114.31
1       -114.47
2       -114.56
3       -114.57
4       -114.57
          ...
16995   -124.26
16996   -124.27
16997   -124.30
16998   -124.30
16999   -124.35
Name: longitude, Length: 17000, dtype: float64

In [15]:
df[['longitude','latitude']]

       longitude  latitude
0        -114.31     34.19
1        -114.47     34.40
2        -114.56     33.69
3        -114.57     33.64
4        -114.57     33.57
...          ...       ...
16995    -124.26     40.58
16996    -124.27     40.69
16997    -124.30     41.84
16998    -124.30     41.80
16999    -124.35     40.54

[17000 rows x 2 columns]

In [16]:
df1=df[['total_rooms','population','households']]

In [17]:
df1.head(10)

   total_rooms  population  households
0       5612.0      1015.0       472.0
1       7650.0      1129.0       463.0
2        720.0       333.0       117.0
3       1501.0       515.0       226.0
4       1454.0       624.0       262.0
5       1387.0       671.0       239.0
6       2907.0      1841.0       633.0
7        812.0       375.0       158.0
8       4789.0      3134.0      1056.0
9       1497.0       787.0       271.0

In [18]:
type(df1)

pandas.core.frame.DataFrame

In [19]:
df['median_income'][1:100:2]

1     1.8200
3     3.1917
5     3.3438
7     1.7083
9     2.1908
11    1.6250
13    3.2120
15    1.6991
17    0.8571
19    1.2656
21    0.8964
23    3.2097
25    3.6528
27    1.9375
29    2.3594
31    1.8958
33    3.3182
35    3.4038
37    2.6172
39    3.3583
41    1.1311
43    3.4107
45    2.1776
47    2.1010
49    2.6250
51    2.1630
53    1.4583
55    1.9911
57    2.3571
59    2.5391
61    2.4063
63    1.7350
65    4.3523
67    3.0091
69    5.4349
71    2.5664
73    1.6351
75    2.8025
77    1.5987
79    1.3882
81    1.3373
83    4.6154
85    4.4821
87    1.7411
89    3.5282
91    3.6042
93    4.3021
95    4.4750
97    1.6635
99    4.8750
Name: median_income, dtype: float64

In [20]:
df[['median_income','households']][1:100:5]

    median_income  households
1          1.8200       463.0
6          2.6768       633.0
11         1.6250       437.0
16         2.9653       256.0
21         0.8964       139.0
26         3.5735       335.0
31         1.8958       241.0
36         1.0000       298.0
41         1.1311       393.0
46         1.6552       410.0
51         2.1630       253.0
56         2.2417       333.0
61         2.4063       318.0
66         1.9464       381.0
71         2.5664       274.0
76         3.8177       421.0
81         1.3373       429.0
86         3.2396       250.0
91         3.6042       208.0
96         3.6597       201.0

In [21]:
df.iloc[1:5]

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0

In [24]:
df.iloc[0:5]

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0

In [26]:
df['population']>500

0         True
1         True
2        False
3         True
4         True
         ...
16995     True
16996     True
16997     True
16998     True
16999     True
Name: population, Length: 17000, dtype: bool

In [27]:
df[df['population']>500]

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0
5,-114.58,33.63,29.0,1387.0,236.0,671.0,239.0,3.3438,74000.0
...,...,...,...,...,...,...,...,...,...
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0

In [29]:
df['New_col'] = df['longitude'] + df['latitude']

In [30]:
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,New_col
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0,-80.12
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0,-80.07
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0,-80.87
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0,-80.93
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0,-81.00

In [31]:
df['New_col1'] = df['total_rooms'] + df['total_bedrooms']

In [32]:
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,New_col,New_col1
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0,-80.12,6895.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0,-80.07,9551.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0,-80.87,894.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0,-80.93,1838.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0,-81.00,1780.0

In [33]:
df.dtypes

longitude             float64
latitude              float64
housing_median_age    float64
total_rooms           float64
total_bedrooms        float64
population            float64
households            float64
median_income         float64
median_house_value    float64
New_col               float64
New_col1              float64
dtype: object

In [35]:
df = df.drop(['New_col'],axis=1)

In [36]:
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,New_col1
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0,6895.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0,9551.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0,894.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0,1838.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0,1780.0

In [37]:
df = df.rename(columns={'total_rooms':'Rooms'})

In [38]:
df

,longitude,latitude,housing_median_age,Rooms,total_bedrooms,population,households,median_income,median_house_value,New_col1
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0,6895.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0,9551.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0,894.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0,1838.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0,1780.0
...,...,...,...,...,...,...,...,...,...,...
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0,2611.0
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0,2877.0
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0,3208.0
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0,3224.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0,2120.0

In [39]:
df['Rooms'][1:100:5]

1     7650.0
6     2907.0
11    1988.0
16    1678.0
21     796.0
26    1602.0
31    1263.0
36    1234.0
41    1523.0
46    1995.0
51    1109.0
56    1715.0
61    1583.0
66    1513.0
71    1540.0
76    2164.0
81    1178.0
86    1365.0
91    1152.0
96    1088.0
Name: Rooms, dtype: float64